# Generated by Django 4.1.2 on 2022-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('mysite1', '0002_salesorger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorger',
            name='product',
            field=models.ManyToManyField(to='Products.product'),
        ),
    ]
